### ISSUE TITLE
Python 2.7.9 support -- AttributeError: 'SafeTransport' object has no attribute 'context'

### ISSUE THREAD

**Issue by tuxmascot** [tcalmant/jsonrpclib#10]
I'm running Python 2.7.8 and I get this issue after running:
`import jsonrpclib`
`server = jsonrpclib.ServerProxy('https://<server>:<port>')`
`print(server.derp)`

and this is the result.

`Traceback (most recent call last):`
  `File "<stdin>", line 1, in <module>`
  `File "/home/tux/code/xmsso/venv/local/lib/python2.7/site-packages/jsonrpclib/jsonrpc.py", line 557, in __call__`
    `return self.__send(self.__name, kwargs)`
  `File "/home/tux/code/xmsso/venv/local/lib/python2.7/site-packages/jsonrpclib/jsonrpc.py", line 434, in _request`
`    response = self._run_request(request)`
  `File "/home/tux/code/xmsso/venv/local/lib/python2.7/site-packages/jsonrpclib/jsonrpc.py", line 467, in _run_request`
`       verbose=self.__verbose`
  `File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request`
`       return self.single_request(host, handler, request_body, verbose)`
  `File "/usr/lib/python2.7/xmlrpclib.py", line 1293, in single_request`
`        h = self.make_connection(host)`
  `File "/usr/lib/python2.7/xmlrpclib.py", line 1509, in make_connection`
`        self._connection = host, HTTPS(chost, None, context=self.context, **(x509 or {}))`
`AttributeError: 'SafeTransport' object has no attribute 'context'`

**Comment by tcalmant** [comment]
Is it a standard distribution of Python ?

I've looked at xmlrpclib.py on Python 2.7.8 and 2.7.6 (Win, Mac & Ubuntu), they both have the following line (without the context argument) at line 1496:
``self._connection = host, HTTPS(chost, None, **(x509 or {}))``

**Comment by tuxmascot** [comment]
Yes, this is a standard distribution.

**Comment by tcalmant** [comment]
According to this [issue22960](http://bugs.python.org/issue22960) [patch](http://bugs.python.org/file37321/issue22960.diff), this is new in the 2.7.9 version of xmlrpclib.

**Comment by tcalmant** [comment]
Patch tested on Python 2.7.8, 2.7.9 and 3.4.2
jsonrpclib-pelix 0.2.3 has been released with this patch.

**Comment by tuxmascot** [comment]
Great! Thanks!
