### ISSUE TITLE
Get ip of caller?

### ISSUE THREAD

**Issue by vimalloc** [tcalmant/jsonrpclib#24]
Is it possible to get the ip address of someone making an rpc call in the registered function?

ex:
```python
def add(a, b):
    print("IP of caller")
    return a + b

if __name__ == '__main__':
    server = PooledJSONRPCServer(("0.0.0.0", 1234))
    server.register_function(add)
    server.serve_forever()
```

**Comment by tcalmant** [comment]
You have to give the ip from a custom request handler.
Take a look at issue #16 to have some ideas on how to implement it :-)

**Comment by vimalloc** [comment]
perfect, thanks! :)
