### ISSUE TITLE
http.client.BadStatusLine error in Python3.4 when calling methods on remote server.

### ISSUE THREAD

**Issue by tuxxy** [tcalmant/jsonrpclib#27]
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>  File "/root/redacted/venv/lib/python3.4/site-packages/jsonrpclib/jsonrpc.py", line 639, in **call**
>     return self.__send(self.__name, args)
>   File "/root/redacted/venv/lib/python3.4/site-packages/jsonrpclib/jsonrpc.py", line 523, in _request
>     response = self._run_request(request)
>   File "/root/redacted/venv/lib/python3.4/site-packages/jsonrpclib/jsonrpc.py", line 556, in _run_request
>     verbose=self.__verbose
>   File "/usr/lib/python3.4/xmlrpc/client.py", line 1131, in request
>     return self.single_request(host, handler, request_body, verbose)
>   File "/root/redacted/venv/lib/python3.4/site-packages/jsonrpclib/jsonrpc.py", line 364, in single_request
>     response = connection.getresponse()
>   File "/usr/lib/python3.4/http/client.py", line 1172, in getresponse
>     response.begin()
>   File "/usr/lib/python3.4/http/client.py", line 351, in begin
>     version, status, reason = self._read_status()
>   File "/usr/lib/python3.4/http/client.py", line 333, in _read_status
>     raise BadStatusLine(line)
> http.client.BadStatusLine: {"result":[{"REDACTED REAL DATA"}],"id":"de3f4da8-3df0-4c07-8074-a9cde173b81b","jsonrpc":"2.0"}

I'm performing the call, and it does seem to be connecting to the server, performing the method, and retrieving that data I want, but it raises the BadStatusLine error.

Any info on what may be causing this?

**Comment by tcalmant** [comment]
Hi,
Could you take a look to the response of the server using tools like Wireshark ?

The ``BadStatusLine`` exception is raised by the builtin HTTP client in the following cases:
* the HTTP version number doesn't start with ``HTTP/`` (first chunk of the response)
* the status code (2nd chunk) is not between 100 and 999
* the status code is not an integer

Although, the line numbers in your stack trace doesn't match the ones on [Python's repo
](https://hg.python.org/cpython/file/3.4/Lib/http/client.py).
Maybe you should take a look into your Python installation, ``"/usr/lib/python3.4/http/client.py`` @ line 333 to check which of these conditions causes the raise of an exception.

**Comment by tuxxy** [comment]
It appears to be throwing the exception due to the version not starting with "HTTP/".
When printing `version`, it looks to be empty.

This works on our server with Python2.7, so we're looking at the server to see if it's sending everything properly. I'll reply with more info once I get it.

Thanks for your help!
