### ISSUE TITLE
SimpleJSONRPCRequestHandler hangs handling UTF-8 content

### ISSUE THREAD

**Issue by gylead** [tcalmant/jsonrpclib#42]
In method SimpleJSONRPCRequestHandler.do_POST size_remaining is lowered by len(chunk[-1]) instead of len(raw_chunk). size_remaining is a byte count while len(chunk[-1]) is a string length. Having a content that contains multi-byte characters the while loop hangs.

**Comment by tcalmant** [comment]
Well spotted !
Thanks :)
