### ISSUE TITLE
Print statements in UJsonHandler

### ISSUE THREAD

**Issue by MarcSchmitzer** [tcalmant/jsonrpclib#52]
There are two print statements in the `UJsonHandler` class in `jsonlib.py`. These get executed at load-time.

**Comment by tcalmant** [comment]
Oups
Thanks for the feedback

**Comment by tcalmant** [comment]
I released a 0.4.3.1 without the print statements

**Comment by MarcSchmitzer** [comment]
Thanks :smile:
